mthropology/config/routes.rb
Mthropology::Application.routes.draw do
  devise_for :users
  root to: 'home_page#index'
  get '/intro' => 'expos#intro'
  post '/search_images' => 'search_images#create'

  resources :expos, :only => :index
  resources :users do
    resources :idealogs, :expos
  end
end

mthropology/app/models/expo.rb
class Expo < ActiveRecord::Base
  belongs_to :user

  has_attached_file :art, styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  }
  validates_attachment_content_type :art, :content_type => /\Aimage\/.*\Z/

  def self.search(search)
    find(:all, :conditions => ['tag LIKE ?', "%#{search}%"])
  end

end

mthropology/app/models/user.rb
class User < ActiveRecord::Base
  has_many :idealogs
  has_many :expos

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

mthropology/app/controllers/application_controller.rb
require 'open-uri'

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper ApplicationHelper

  before_action :get_remote_images

  def after_sign_in_path_for(resource)
    @user_path
  end

# bad smell: duplicate code
  def get_remote_images
    if params[:term] == nil
      doc = Nokogiri::XML(open("http://www.vam.ac.uk/api/xml/museumobject/"))
      parse_xml(doc)
    else
      doc = Nokogiri::XML(open("http://www.vam.ac.uk/api/xml/museumobject/?q=#{params[:term]}&images=1"))
      parse_xml(doc)
    end
  end

# solution: extract method
  def parse_xml(doc)
    id = doc.xpath("//primary_image_id")
    string = id.inner_text
    keys = string.scan(/.{1,10}/)
    url = keys.map{ |key| key[0..-5]}
    @sources = keys.zip(url).map {|key, url| "http://media.vam.ac.uk/media/thira/collection_images/#{url}/#{key}.jpg"}
    @desc = doc.xpath("//descriptive_line")
  end
end

mthropology/app/controllers/expos_controller.rb
class ExposController < ApplicationController

  before_action :get_user

  def index
    if params[:search]
      @expos = Expo.search(params[:search])
    else
      @expos = Expo.includes(:user).all
    end
  end

  def new
    @expo= Expo.new
  end

  def create
    @user.expos << Expo.create!(expo_params)
    redirect_to user_path(@user.id)
  end

  def show
    @expo = Expo.find(params[:id])
  end

  def edit
    @expo = Expo.find(params[:id])
  end

  def update
    @expo = Expo.find(params[:id])
    @expo.update_attributes(expo_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @expo = Expo.find(params[:id])
    @expo.destroy
    redirect_to user_path(@user.id)
  end

  def intro
  end

  private

  def expo_params
    params.require(:expo).permit(:title, :body, :art, :url, :tag, :user_id, :id, :created_at)
  end

  def get_user
    @user= User.find(params[:user_id]) if params.key?(:user_id)
  end

end

mthropology/app/controllers/home_page_controller.rb
class HomePageController < ApplicationController

  def index
     render :layout => 'application'
  end

end

mthropology/app/controllers/idealogs_controller.rb
class IdealogsController < ApplicationController
 before_action :get_user

  def index
    @idealogs = Idealog.includes(:user).all
  end

  def new
    @idealog = Idealog.new
  end

  def create
    @user.idealogs << Idealog.create!(idealog_params)
    redirect_to user_path(@user.id)
  end

  def show
    @idealog = Idealog.find(params[:id])
  end

  def edit
    @idealog = Idealog.find(params[:id])
  end

  def update
    @idealog = Idealog.find(params[:id])
    @idealog.update_attributes(idealog_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @idealog = Idealog.find(params[:id])
    @idealog.destroy
    redirect_to user_path(@user.id)
  end

  private

  def idealog_params
    params.require(:idealog).permit(:title, :body, :tag, :user_id, :id, :created_at)
  end

  def get_user
    @user= User.find(params[:user_id]) if params.key?(:user_id)
  end

end

mthropology/app/controllers/search_images_controller.rb
class SearchImagesController < ApplicationController

  def create
    redirect_to "#{request.referer.split('?').first}?term=#{params[:term]}"
  end
end

mthropology/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def new
    @user.id = current_user.id
    @user = User.new
  end

  def create
    @user.id = current_user.id
    @user = User.new(user_params)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :id)
  end

end

mthropology/app/helpers/application_helper.rb
module ApplicationHelper

end

mthropology/app/views/expos/_expo_form.html.erb
<%= form_for [@user, @expo] do |form| %>
  <% form.label :title %>
    <p><%= form.text_area :title, placeholder: "Title", :cols => "70", :rows => "1" %></p>
  <% form.label :body %>
    <p><%= form.text_area :body, placeholder: "Ideas", :cols => "70", :rows => "10" %></p>
  <% form.label :art %>
    <p><%= form.file_field :art%></p>
  <% form.label :url %>
    <p><%= form.text_area :url, placeholder: "Artifact Link", :cols => "70", :rows => "1" %></p>
  <% form.label :tag %>
    <p><%= form.text_area :tag, placeholder: "Tag", :cols => "70", :rows => "1" %></p>
    <p><%= form.submit %></p>
<% end %>

mthropology/app/views/expos/edit.html.erb
<div class="container">
  <h2>Edit Exhibit</h2>
    <%= render partial: 'expo_form' %>
</div>

mthropology/app/views/expos/index.html.erb
<div class="container">
  <h2>Exhibits</h2>
    <div class="form-inline" role="form">
      <div class="form-group">
        <%= form_tag expos_path, :method => 'get' do %>
          <%= text_field_tag(:search, nil, placeholder: "tags") %></div>
        <% end %>
         <div class="btn">
          <%= submit_tag "search" %>
        </div>
      </div>
    </div>
    <br>
  <div id="yield">
    <dl>
      <% @expos.each do |expo| %>
        <dt> Title: <%= link_to expo.title, user_expo_path(expo.user.id, expo.id)%></dt>
          <dd>By: <%=expo.user.email%> </dd>
            <p class="tag"> Tags: <%= expo.tag %></p>
            <p class="time"> Created <%= time_ago_in_words(expo.created_at)%> ago</p>
          <br>
      <% end %>
    </dl>
  </div>
</div>

mthropology/app/views/expos/new.html.erb
<div class="container">
  <h2>New Exhibit</h2>
    <%= render partial: 'expo_form' %>
</div>

mthropology/app/views/expos/show.html.erb
<div class="container">
  <div id="yield">
    <header>
      <h2>Title: <%= @expo.title%></h2>
    </header>
    <body>
      <p class="body">Content: <%= @expo.body %></p>
      <p><%= image_tag @expo.art.url(:medium) %></p>
      <p class="tag">Tags: <%= @expo.tag %></p>
      <p class="url"> URL: <a href="<%= @expo.url %>">Inspiration</a></p>
    </body>
    <div class="login">
      <% if user_signed_in? && @expo.user.id == current_user.id %>
      <%= link_to "Edit", edit_user_expo_path(@expo.user.id, @expo.id) %><br>
      <%= link_to "Delete", user_expo_path(@expo.user.id, @expo.id), method: :delete %><br>
      <% end %>
  </div>
</div>

mthropology/app/views/idealogs/_idea_form.html.erb
<%= form_for [@user, @idealog] do |form| %>
  <p><% form.label :title %><br>
    <%= form.text_area :title, placeholder: "Title",:cols => "70", :rows => "1" %></p>
  <p><% form.label :body %><br>
    <%= form.text_area :body, placeholder: "Ideas", :cols => "70", :rows => "10" %></p>
  <p><% form.label :tag %><br>
    <%= form.text_area :tag, placeholder: "Tag", :cols => "70", :rows => "1"%></p>
  <p><%= form.submit %></p>
<% end %>

mthropology/app/views/idealogs/edit.html.erb
<div class="container">
  <h2>Edit your idea</h2>
    <%= render partial: 'idea_form' %>
</div>

mthropology/app/views/idealogs/new.html.erb
<div class="container">
  <h2>Log a new idea</h2>
    <%= render partial: 'idea_form' %>
</div>

mthropology/app/views/idealogs/show.html.erb
<div class="container">
  <div id="yield">
    <header>
      <h3 class="post-title">
        <%= @idealog.title%>
      </h3>
    </header>
    <p class="body">
      <%= @idealog.body %>
    </p>
    <div class="user-nav">
      <%= link_to "Edit", edit_user_idealog_path(@idealog.user.id, @idealog.id) %><br>
      <%= link_to "Delete", user_idealog_path(@idealog.user.id, @idealog.id), method: :delete %><br>
      <%= link_to "Log a new idea", new_user_idealog_path(@user.id) %><br>
    </div>
  </div>
</div>

mthropology/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>mthropology</title>
      <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
      <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
      <%= csrf_meta_tags %>
      <link href='http://fonts.googleapis.com/css?family=Nova+Square' rel='stylesheet' type='text/css'>
  </head>
  <header>
    <div class="jumbotron">
      <div class="navbar navbar-fixed-top">
        <ul class="nav navbar-nav">
          <li class="nav"><a href="http://www.vam.ac.uk/">V&A</a></li>
          <li class="nav"><%= link_to "home", root_url %></li>
          <li class="nav"><%= link_to "introduction", intro_path %></li>
          <li class="nav"><%= link_to "exhibits", expos_path %></li>
          <% if user_signed_in? %>
            <li class="nav"><%= link_to "portfolio", user_path(current_user.id) %></li>
            <li class="nav"><%= link_to "sign out", destroy_user_session_path,  :method => :delete %></li>
          <% else %>
            <li class="nav"><%= link_to "sign up", new_user_registration_path %></li>
            <li class="nav"><%= link_to "sign in", user_session_path %></li>
          <% end %>
        </ul>
        <div class="navbar-form navbar-right" role="search">
          <%= form_tag('/search_images') do %>
          <%= text_field_tag :term, nil, placeholder: 'V&A collection' %>
            <div class="btn">
        </div>
              <%= submit_tag "search" %>
          <% end %>
        </div>
      </div>
        <h1 id="title">mthropology</h1>
          <p id="tagline">inspire and display dialogues between people and their things</p>
    </div>
  </header>
  <body>
     <% unless params[:controller] == "home_page" && params[:action] == 'index' %>
      <div id="sidebar">
        <% @sources.zip(@desc).each do |source, desc| %>
          <a href="<%= source %>"><img src="<%= source %>" alt="<%= desc.inner_text.to_s%>" title="<%= desc.inner_text.to_s%>" width="300"></a>
        <% end %>
      </div>
      <% else %>
       <!-- This is the code for home#index -->
        <div id="homepage">
          <ul id="grid">
            <% @sources.zip(@desc).each do |source, desc| %>
              <li class="object"><a href="<%= source %>"><img src="<%= source %>" alt="<%= desc.inner_text.to_s%>" title="<%= desc.inner_text.to_s%>" height=90% width=90%></a></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    <div id="yield">
      <%= yield %>
    </div>
  </body>
</html>

mthropology/app/views/users/show.html.erb
<div class="container">
  <div id="yield">
  <header>
    <h5 class="login-status">Login as: <%=@user.email%></h5>
  </header>
    <h3>Ideas</h3>
      <% @user.idealogs.each do |idealog| %>
        <ul class="idealog-list">
          <li><%=link_to idealog.title, user_idealog_path(idealog.user_id, idealog.id) %> Created <%= time_ago_in_words(idealog.created_at)%> ago</li>
        </ul>
      <% end %>
      <br>
    <%= link_to "Log a new idea", new_user_idealog_path(@user.id) %>
      <br>
      <br>
    <h3>Exhibits</h3>
      <% @user.expos.each do |expo| %>
        <ul class="expo-list">
          <li><%=link_to expo.title, user_expo_path(expo.user_id, expo.id) %>  Created <%= time_ago_in_words(expo.created_at)%> ago</li>
        </ul>
      <% end %>
      <br>
    <%= link_to "Display a new exhibit", new_user_expo_path(@user.id) %>
      <br>
  </div>
</div>